-- 1 LENGTH(STR)

SELECT LENGTH("HELLO");
SELECT LENGTH('😃');

-- 2 CHAR_LENGTH(STR)
SELECT CHAR_LENGTH('HELO');
SELECT CHAR_LENGTH('😃');

-- 3- CONCAT(STR1,STR2...)
SELECT CONCAT('MY','NAME','IS');
SELECT CONCAT('MY',' ','NAME',' ','IS');

-- 4 CONCAT_WITH_SEPARATOR(SEPARATOR,STR1,STR2,...)

SELECT CONCAT_WS('-','2000','10',14);
SELECT CONCAT_WS(',','DILEEP','ABID','RAVINDRANATH');

-- 5 UPPER 
SELECT UPPER('RAVINDRANTH');

-- 6 LOWER

SELECT LOWER('RAVINDRANTH');

-- 7 LEFT (STR,LEN)
SELECT LEFT('RAVINDRANATH', 4);

-- 8 RIGHT (str,len)
SELECT RIGHT('RAVINDRANATH', 4);

-- 9 SUBSTRING(STR,START,LEN)
SELECT SUBSTRING('ABID IS A GOOD BOY',4);
SELECT SUBSTRING('ABID IS A GOOD BOY',6,8);

-- 10 LOCATE (SUBSTR,STR) / POSITION(SUBSTR IN STR)

SELECT LOCATE('B','ABID IS A GOOD BOY');

SELECT POSITION('D' IN 'ABID IS A GOOD BOY');

-- 11 INSTR(STR , SUBSTR)

SELECT INSTR('DATABASE' , "A");

-- 12 REPLACE(STR,FROM_STR,TO_STR)

SELECT REPLACE('RAVINDRANATH' ,'A' , 'D');

-- 13 TRIM([LEADING | TRAILING | BOTH])
SELECT TRIM(' HELLO      WORLD ');

SELECT TRIM(BOTH 'X' FROM 'XXXXXXXXXXXHEXXLLXOXW');

SELECT TRIM(LEADING 'X' FROM 'XRAVINDRANATH');

SELECT TRIM(TRAILING 'H' FROM 'RAVINDRANATH');

-- 14-LTRIM(STR)

SELECT LTRIM('D  RAVI');

-- 15 RTRIM(STR)

SELECT RTRIM('RAVI   D');

-- 16 REVERSE (STR)
SELECT REVERSE('RAVINDRANTH');

-- 17 LPAD(STR,LEN,PAD STR)

SELECT LPAD('RAVINDRANTH' ,20, '0');

-- 18 RPAD(STR,LEN,PAD STR)

SELECT RPAD('RAVINDRANTH' ,13, '-');

-- 19 QUOTE(STR)

SELECT QUOTE("IT'S RAINING");

-- 20 SPACE(N)

SELECT CONCAT('----',SPACE(10),'MY SQL PROGRAMMING', SPACE(5),'IS VERY HARD TO LEARN');

-- 21 REPEAT(STR,COUNT)
SELECT REPEAT('MYSQL-',5);


